#ifndef NVIC_TYPES_H
#define NVIC_TYPES_H

enum NVIC_INTERRUPT_PRIORITY{

    NVIC_HIGHEST_PRIORITY = 0x0,
    NVIC_PRIORITY_1 = 0x1,
    NVIC_PRIORITY_2 = 0x2,
    NVIC_PRIORITY_3 = 0x3,
    NVIC_PRIORITY_4 = 0x4,
    NVIC_PRIORITY_5 = 0x5,
    NVIC_PRIORITY_6 = 0x6,
    NVIC_PRIORITY_7 = 0x7,
    NVIC_PRIORITY_8 = 0x8,
    NVIC_PRIORITY_9 = 0x9,
    NVIC_PRIORITY_10 = 0xA,
    NVIC_PRIORITY_11 = 0xB,
    NVIC_PRIORITY_12 = 0xC,
    NVIC_PRIORITY_13 = 0xD,
    NVIC_PRIORITY_14 = 0xE,
    NVIC_PRIORITY_15 = 0xF,
    NVIC_PRIORITY_MSK = 0xF,
};


#endif